/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_telegram_mtproto_OpenSSL */

#ifndef _Included_org_telegram_mtproto_OpenSSL
#define _Included_org_telegram_mtproto_OpenSSL
#ifdef __cplusplus
extern "C" {
#endif
#undef org_telegram_mtproto_OpenSSL_AES_ENCRYPT
#define org_telegram_mtproto_OpenSSL_AES_ENCRYPT 1L
#undef org_telegram_mtproto_OpenSSL_AES_DECRYPT
#define org_telegram_mtproto_OpenSSL_AES_DECRYPT 0L
/*
 * Class:     org_telegram_mtproto_OpenSSL
 * Method:    AES_ige_encrypt
 * Signature: (Ljava/nio/ByteBuffer;[B[BIII)V
 */
JNIEXPORT void JNICALL Java_org_telegram_mtproto_OpenSSL_AES_1ige_1encrypt
  (JNIEnv *, jclass, jobject, jbyteArray, jbyteArray, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
