<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="DotNext" />
    <None Remove="DotNext.IO" />
    <None Remove="DotNext.Unsafe" />
    <None Remove="System.Security.Cryptography.OpenSsl" />
    <None Remove="Portable.BouncyCastle" />
    <None Remove="BouncyCastle" />
    <None Remove="BouncyCastle.NetCore" />
    <None Remove="Exceptions\" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="DotNext" Version="6.3.0" />
    <PackageReference Include="DotNext.IO" Version="6.3.0" />
    <PackageReference Include="DotNext.Unsafe" Version="6.3.0" />
    <PackageReference Include="Portable.BouncyCastle" Version="1.9.0" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Ferrite.Utils\Ferrite.Utils.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Exceptions\" />
  </ItemGroup>
</Project>
