<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="DotNext" />
    <None Remove="DotNext.IO" />
    <None Remove="DotNext.Unsafe" />
    <None Remove="Serilog" />
    <None Remove="Serilog.Sinks.File" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="DotNext" Version="6.3.0" />
    <PackageReference Include="DotNext.IO" Version="6.3.0" />
    <PackageReference Include="DotNext.Unsafe" Version="6.3.0" />
    <PackageReference Include="Serilog" Version="4.3.1" />
    <PackageReference Include="Serilog.Sinks.File" Version="7.0.0" />
  </ItemGroup>
  <ItemGroup>
    <None Include="..\.editorconfig" />
  </ItemGroup>
</Project>
