// SPDX-License-Identifier: AGPL-3.0-or-later
// Copyright (C) 2022-2026 Aykut Alparslan KOC
//  <auto-generated>
//  This file was auto-generated by the Ferrite TL Generator.
//  Please do not modify as all changes will be lost.
//  <auto-generated/>

#nullable enable

using System.Buffers;
using System.Runtime.InteropServices;
using Ferrite.Utils;
using DotNext.Buffers;

namespace Ferrite.TL;

public readonly ref struct Error
{
    private readonly Span<byte> _buff;
    private readonly IMemoryOwner<byte>? _memory;
    public Error(int code, ReadOnlySpan<byte> text)
    {
        var length = GetRequiredBufferSize(text.Length);
        _memory = UnmanagedMemoryPool<byte>.Shared.Rent(length);
        _memory.Memory.Span.Clear();
        _buff = _memory.Memory.Span[..length];
        SetConstructor(unchecked((int)0xc4b9f9bb));
        Set_code(code);
        Set_text(text);
    }
    public Error(Span<byte> buff)
    {
        _buff = buff;
    }
    
    public readonly int Constructor => MemoryMarshal.Read<int>(_buff);

    private void SetConstructor(int constructor)
    {
        MemoryMarshal.Write(_buff.Slice(0, 4), ref constructor);
    }
    public int Length => _buff.Length;
    public ReadOnlySpan<byte> ToReadOnlySpan() => _buff;
    public TLBytes? TLBytes => _memory != null ? new TLBytes(_memory, 0, _buff.Length) : null;
    public static Span<byte> Read(Span<byte> data, int offset)
    {
        var bytesRead = GetOffset(3, data[offset..]);
        if (bytesRead > data.Length + offset)
        {
            return Span<byte>.Empty;
        }
        return data.Slice(offset, bytesRead);
    }

    public static int GetRequiredBufferSize(int len_text)
    {
        return 4 + 4 + BufferUtils.CalculateTLBytesLength(len_text);
    }
    public static int ReadSize(Span<byte> data, int offset)
    {
        return GetOffset(3, data[offset..]);
    }
    public readonly int code => MemoryMarshal.Read<int>(_buff[GetOffset(1, _buff)..]);
    private void Set_code(int value)
    {
        MemoryMarshal.Write(_buff[GetOffset(1, _buff)..], ref value);
    }
    public ReadOnlySpan<byte> text => BufferUtils.GetTLBytes(_buff, GetOffset(2, _buff));
    private void Set_text(ReadOnlySpan<byte> value)
    {
        if(value.Length == 0)
        {
            return;
        }
        var offset = GetOffset(2, _buff);
        var lenBytes = BufferUtils.WriteLenBytes(_buff, value, offset);
        if(_buff.Length < offset + lenBytes + value.Length) return;
        value.CopyTo(_buff[(offset + lenBytes)..]);
    }
    private static int GetOffset(int index, Span<byte> buffer)
    {
        int offset = 4;
        if(index >= 2) offset += 4;
        if(index >= 3) offset += BufferUtils.GetTLBytesLength(buffer, offset);
        return offset;
    }
    public ref struct TLObjectBuilder
    {
        private int _code;
        public TLObjectBuilder with_code(int value)
        {
            _code = value;
            return this;
        }
        private ReadOnlySpan<byte> _text;
        public TLObjectBuilder with_text(ReadOnlySpan<byte> value)
        {
            _text = value;
            return this;
        }
        public Error Build()
        {
            return new Error(_code, _text);
        }
    }

    public static TLObjectBuilder Builder()
    {
        return new TLObjectBuilder();
    }
    public void Dispose()
    {
        _memory?.Dispose();
    }
}
