// SPDX-License-Identifier: AGPL-3.0-or-later
// Copyright (C) 2022-2026 Aykut Alparslan KOC

using Ferrite.TL;
using Ferrite.TL.Schema;

namespace Ferrite.Core.Execution.Functions.BaseLayer;

public static class DisabledMethods
{
    private static readonly string[] Namespaces =
    [
        "bots", "fragment", "payments", "premium", "smsjobs", "stories",
    ];

    private static readonly string[] Methods =
    [
        "account.acceptAuthorization",
        "account.confirmBotConnection",
        "account.createBusinessChatLink",
        "account.deleteBusinessChatLink",
        "account.deletePasskey",
        "account.deleteSecureValue",
        "account.deleteWebBrowserSettingsExceptions",
        "account.disablePeerConnectedBot",
        "account.editBusinessChatLink",
        "account.getAllSecureValues",
        "account.getAuthorizationForm",
        "account.getBotBusinessConnection",
        "account.getBusinessChatLinks",
        "account.getConnectedBots",
        "account.getPaidMessagesRevenue",
        "account.getPasskeys",
        "account.getSecureValue",
        "account.getUniqueGiftChatThemes",
        "account.getWebBrowserSettings",
        "account.initPasskeyRegistration",
        "account.registerPasskey",
        "account.resolveBusinessChatLink",
        "account.saveSecureValue",
        "account.toggleConnectedBotPaused",
        "account.toggleNoPaidMessagesException",
        "account.toggleSponsoredMessages",
        "account.toggleWebBrowserSettingsException",
        "account.updateBusinessAwayMessage",
        "account.updateBusinessGreetingMessage",
        "account.updateBusinessIntro",
        "account.updateBusinessLocation",
        "account.updateBusinessWorkHours",
        "account.updateConnectedBot",
        "account.updateWebBrowserSettings",
        "aicompose.createTone",
        "aicompose.deleteTone",
        "aicompose.getTone",
        "aicompose.getToneExample",
        "aicompose.getTones",
        "aicompose.saveTone",
        "aicompose.updateTone",
        "auth.checkPaidAuth",
        "auth.finishFirebasePnvLogin",
        "auth.finishPasskeyLogin",
        "auth.firebasePnvSignUp",
        "auth.importBotAuthorization",
        "auth.initFirebasePnvLogin",
        "auth.initPasskeyLogin",
        "channels.restrictSponsoredMessages",
        "channels.updatePaidMessagesPrice",
        "communities.create",
        "communities.getJoinedCommunities",
        "communities.getParticipantJoinedChats",
        "communities.getPeerLinkRequests",
        "communities.toggleAllPeerLinkRequestApproval",
        "communities.toggleCommunityCollapsedInDialogs",
        "communities.toggleParticipantBanned",
        "communities.togglePeerLink",
        "communities.togglePeerLinkRequestApproval",
        "contacts.getSponsoredPeers",
        "contacts.updateContactNote",
        "ephemeral.deleteAllWelcomeMessages",
        "ephemeral.deleteMessage",
        "ephemeral.deleteWelcomeMessage",
        "ephemeral.editMessage",
        "ephemeral.getCallbackAnswer",
        "ephemeral.getWelcomeMessages",
        "ephemeral.reportMessage",
        "ephemeral.sendMessage",
        "help.editUserInfo",
        "help.getPremiumPromo",
        "help.getSupport",
        "help.getSupportName",
        "help.getUserInfo",
        "help.setBotUpdatesStatus",
        "invokeWithBusinessConnection",
        "messages.acceptUrlAuth",
        "messages.addPollAnswer",
        "messages.appendTodoList",
        "messages.checkHistoryImport",
        "messages.checkHistoryImportPeer",
        "messages.checkQuickReplyShortcut",
        "messages.checkUrlAuthMatchCode",
        "messages.clickSponsoredMessage",
        "messages.composeMessageWithAI",
        "messages.composeRichMessageWithAI",
        "messages.declineUrlAuth",
        "messages.deleteFactCheck",
        "messages.deleteParticipantReaction",
        "messages.deleteParticipantReactions",
        "messages.deletePollAnswer",
        "messages.deleteQuickReplyMessages",
        "messages.deleteQuickReplyShortcut",
        "messages.editChatParticipantRank",
        "messages.editFactCheck",
        "messages.editInlineBotMessage",
        "messages.editQuickReplyShortcut",
        "messages.getAttachMenuBot",
        "messages.getAttachMenuBots",
        "messages.getBotApp",
        "messages.getBotCallbackAnswer",
        "messages.getDefaultTagReactions",
        "messages.getEmojiGameInfo",
        "messages.getExtendedMedia",
        "messages.getFactCheck",
        "messages.getFutureChatCreatorAfterLeave",
        "messages.getGameHighScores",
        "messages.getInlineBotResults",
        "messages.getInlineGameHighScores",
        "messages.getPaidReactionPrivacy",
        "messages.getPersonalChannelHistory",
        "messages.getPreparedInlineMessage",
        "messages.getQuickReplies",
        "messages.getQuickReplyMessages",
        "messages.getRichMessage",
        "messages.getSavedReactionTags",
        "messages.getSponsoredMessages",
        "messages.getUnreadPollVotes",
        "messages.initHistoryImport",
        "messages.prolongWebView",
        "messages.rateTranscribedAudio",
        "messages.readPollVotes",
        "messages.reorderQuickReplies",
        "messages.reportMusicListen",
        "messages.reportReadMetrics",
        "messages.reportSponsoredMessage",
        "messages.requestAppWebView",
        "messages.requestChatJoinWebView",
        "messages.requestMainWebView",
        "messages.requestSimpleWebView",
        "messages.requestUrlAuth",
        "messages.requestWebView",
        "messages.savePreparedInlineMessage",
        "messages.sendBotRequestedPeer",
        "messages.sendInlineBotResult",
        "messages.sendPaidReaction",
        "messages.sendQuickReplyMessages",
        "messages.sendWebViewData",
        "messages.sendWebViewResultMessage",
        "messages.setBotCallbackAnswer",
        "messages.setBotGuestChatResult",
        "messages.setBotPrecheckoutResults",
        "messages.setBotShippingResults",
        "messages.setGameScore",
        "messages.setInlineBotResults",
        "messages.setInlineGameScore",
        "messages.startBot",
        "messages.startHistoryImport",
        "messages.summarizeText",
        "messages.toggleBotInAttachMenu",
        "messages.togglePaidReactionPrivacy",
        "messages.togglePeerTranslations",
        "messages.toggleSuggestedPostApproval",
        "messages.toggleTodoCompleted",
        "messages.transcribeAudio",
        "messages.translateRichMessage",
        "messages.translateText",
        "messages.updateSavedReactionTag",
        "messages.uploadImportedMedia",
        "messages.viewSponsoredMessage",
        "phone.deleteGroupCallMessages",
        "phone.deleteGroupCallParticipantMessages",
        "phone.getGroupCallStars",
        "phone.saveDefaultSendAs",
        "phone.sendGroupCallEncryptedMessage",
        "phone.sendGroupCallMessage",
        "stats.getPollStats",
        "stats.getStoryPublicForwards",
        "stats.getStoryStats",
        "upload.getCdnFile",
        "upload.getCdnFileHashes",
        "upload.getWebFile",
        "upload.reuploadCdnFile",
        "users.setSecureValueErrors",
        "users.suggestBirthday",
    ];

    private static readonly (int Layer, string Method)[] HistoricalMethods =
    [
        (150, "channels.getSponsoredMessages"),
        (150, "channels.viewSponsoredMessage"),
        (150, "help.getAppChangelog"),
        (150, "payments.canPurchasePremium"),
        (215, "channels.createForumTopic"),
        (215, "channels.deleteTopicHistory"),
        (215, "channels.editForumTopic"),
        (215, "channels.getForumTopics"),
        (215, "channels.getForumTopicsByID"),
        (215, "channels.reorderPinnedForumTopics"),
        (215, "channels.updatePinnedForumTopic"),
        (222, "channels.editCreator"),
        (222, "channels.getFutureCreatorAfterLeave"),
    ];

    public static FunctionKey[] Keys { get; } = Resolve();

    private static FunctionKey[] Resolve()
    {
        LayerSchema schema = LayerSchemaCatalog.Create(LayerSchemaCatalog.BaseLayer);
        IEnumerable<int> current = schema.Methods
            .Where(method => Namespaces.Contains(NamespaceOf(method.Name)))
            .Select(method => method.Id)
            .Concat(Methods.Select(name => schema.GetMethod(name).Id));
        IEnumerable<int> historical = HistoricalMethods.Select(entry =>
            LayerSchemaCatalog.Create(entry.Layer).GetMethod(entry.Method).Id);
        return current.Concat(historical).Select(id => new FunctionKey(id)).ToArray();
    }

    private static string NamespaceOf(string name)
    {
        int dot = name.IndexOf('.');
        return dot < 0 ? string.Empty : name.Substring(0, dot);
    }
}
