<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>preview</LangVersion>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>
  <ItemGroup>
    <None Remove="DotNext" />
    <None Remove="DotNext.IO" />
    <None Remove="DotNext.Unsafe" />
    <None Remove="Microsoft.Extensions.Primitives" />
    <None Remove="Microsoft.Net.Http.Headers" />
    <None Remove="Microsoft.AspNetCore.Http" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="DotNext" Version="6.3.0" />
    <PackageReference Include="DotNext.IO" Version="6.3.0" />
    <PackageReference Include="DotNext.Unsafe" Version="6.3.0" />
    <PackageReference Include="Microsoft.Extensions.Primitives" Version="10.0.9" />
  </ItemGroup>
</Project>
